### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by solthoth** [CenturyLinkLabs/ca-certs-base-image#3]
Hello,

We were wondering if you could help us out, or at least point us in a good direction to head towards. We have been using your base container [centurylinkslabs/ca-certs](https://hub.docker.com/r/centurylink/ca-certs/) for our Linux containers, but we have been tasked to migrated towards windows containers. Our question is this: do you have a windows based container publicly available anywhere, or know where to possibly acquire one?

**Comment by rupakg** [comment]
Short answer will be No.
